### ISSUE TITLE
Extra point at the end of cardinal spline interpolated curve

### ISSUE THREAD

**Issue by lassoan** [SlicerIGT/SlicerMarkupsToModel#1]
A random point is added to the end of curves if cardinal spline interpolation is used.

**Comment by lassoan** [comment]
Maybe it was just an update issue that was fixed by https://github.com/SlicerIGT/SlicerMarkupsToModel/commit/7ef4456a0d98e259ee439f7e4571791dc475d10a

Anyway, it would be good to have a look at the data allocation and indexing code in MarkupsToModel\Logic\CreateCurveUtil.h

**Comment by tavaughan** [comment]
I haven't been able to reproduce this issue yet. Confirm it is still present?

Note: I was able to reproduce the crashing in an earlier version of the module (before commit 2328417ffe4226cd49abcbb175ee45b1a5f64ea1 ).

**Comment by lassoan** [comment]
Thanks for testing. I'm closing this issue then.
